<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmPrintPreview
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmPrintPreview))
        Panel3 = New Panel()
        lblPrintDate = New Label()
        Label20 = New Label()
        Label18 = New Label()
        Panel8 = New Panel()
        lblAdminID = New Label()
        lblAdminName = New Label()
        Label14 = New Label()
        Label15 = New Label()
        Button3 = New Button()
        Panel7 = New Panel()
        lblNewQuan = New Label()
        lblChangeQuan = New Label()
        lblPreviousQuan = New Label()
        Label16 = New Label()
        Label17 = New Label()
        Label19 = New Label()
        Button2 = New Button()
        Panel6 = New Panel()
        lblReason = New Label()
        lblSize = New Label()
        lblGender = New Label()
        lblLevel = New Label()
        lblItemName = New Label()
        lblUniformID = New Label()
        Label13 = New Label()
        Label12 = New Label()
        Label10 = New Label()
        Label9 = New Label()
        Label11 = New Label()
        Label8 = New Label()
        Button1 = New Button()
        Panel5 = New Panel()
        lblLogId = New Label()
        lblAction = New Label()
        Label7 = New Label()
        lblTime = New Label()
        lblDate = New Label()
        Label6 = New Label()
        Label5 = New Label()
        Label4 = New Label()
        Panel4 = New Panel()
        Label3 = New Label()
        Label2 = New Label()
        Panel2 = New Panel()
        Label1 = New Label()
        Panel1 = New Panel()
        btnPrint = New Button()
        PrintDocument1 = New Printing.PrintDocument()
        PrintPreviewDialog1 = New PrintPreviewDialog()
        Label21 = New Label()
        Panel3.SuspendLayout()
        Panel8.SuspendLayout()
        Panel7.SuspendLayout()
        Panel6.SuspendLayout()
        Panel5.SuspendLayout()
        Panel4.SuspendLayout()
        Panel2.SuspendLayout()
        Panel1.SuspendLayout()
        SuspendLayout()
        ' 
        ' Panel3
        ' 
        Panel3.BackColor = Color.WhiteSmoke
        Panel3.Controls.Add(Label21)
        Panel3.Controls.Add(lblPrintDate)
        Panel3.Controls.Add(Label20)
        Panel3.Controls.Add(Label18)
        Panel3.Controls.Add(Panel8)
        Panel3.Controls.Add(Panel7)
        Panel3.Controls.Add(Panel6)
        Panel3.Controls.Add(Panel5)
        Panel3.Controls.Add(Panel4)
        Panel3.Location = New Point(18, 17)
        Panel3.Name = "Panel3"
        Panel3.Size = New Size(456, 584)
        Panel3.TabIndex = 114
        ' 
        ' lblPrintDate
        ' 
        lblPrintDate.AutoSize = True
        lblPrintDate.Font = New Font("Arial Rounded MT Bold", 9.75F, FontStyle.Regular, GraphicsUnit.Point, CByte(0))
        lblPrintDate.ForeColor = Color.Firebrick
        lblPrintDate.Location = New Point(100, 555)
        lblPrintDate.Name = "lblPrintDate"
        lblPrintDate.Size = New Size(13, 15)
        lblPrintDate.TabIndex = 18
        lblPrintDate.Text = "  "
        ' 
        ' Label20
        ' 
        Label20.AutoSize = True
        Label20.Font = New Font("Arial Rounded MT Bold", 9.75F, FontStyle.Regular, GraphicsUnit.Point, CByte(0))
        Label20.Location = New Point(23, 555)
        Label20.Name = "Label20"
        Label20.Size = New Size(83, 15)
        Label20.TabIndex = 17
        Label20.Text = " Print Date: "
        ' 
        ' Label18
        ' 
        Label18.AutoSize = True
        Label18.Font = New Font("Arial Rounded MT Bold", 9.75F, FontStyle.Regular, GraphicsUnit.Point, CByte(0))
        Label18.Location = New Point(25, 535)
        Label18.Name = "Label18"
        Label18.Size = New Size(101, 15)
        Label18.TabIndex = 16
        Label18.Text = "Generated by: "
        ' 
        ' Panel8
        ' 
        Panel8.BackColor = Color.LightGray
        Panel8.Controls.Add(lblAdminID)
        Panel8.Controls.Add(lblAdminName)
        Panel8.Controls.Add(Label14)
        Panel8.Controls.Add(Label15)
        Panel8.Controls.Add(Button3)
        Panel8.Location = New Point(25, 429)
        Panel8.Name = "Panel8"
        Panel8.Size = New Size(398, 93)
        Panel8.TabIndex = 15
        ' 
        ' lblAdminID
        ' 
        lblAdminID.AutoSize = True
        lblAdminID.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblAdminID.Location = New Point(81, 63)
        lblAdminID.Name = "lblAdminID"
        lblAdminID.Size = New Size(16, 15)
        lblAdminID.TabIndex = 16
        lblAdminID.Text = "   "
        ' 
        ' lblAdminName
        ' 
        lblAdminName.AutoSize = True
        lblAdminName.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblAdminName.Location = New Point(109, 42)
        lblAdminName.Name = "lblAdminName"
        lblAdminName.Size = New Size(16, 15)
        lblAdminName.TabIndex = 15
        lblAdminName.Text = "   "
        ' 
        ' Label14
        ' 
        Label14.AutoSize = True
        Label14.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label14.Location = New Point(12, 42)
        Label14.Name = "Label14"
        Label14.Size = New Size(98, 15)
        Label14.TabIndex = 9
        Label14.Text = "Performed by:"
        ' 
        ' Label15
        ' 
        Label15.AutoSize = True
        Label15.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label15.Location = New Point(12, 63)
        Label15.Name = "Label15"
        Label15.Size = New Size(69, 15)
        Label15.TabIndex = 10
        Label15.Text = "Admin ID:"
        ' 
        ' Button3
        ' 
        Button3.BackColor = Color.DarkSlateGray
        Button3.FlatStyle = FlatStyle.Flat
        Button3.Font = New Font("Arial Rounded MT Bold", 9.75F, FontStyle.Regular, GraphicsUnit.Point, CByte(0))
        Button3.ForeColor = Color.White
        Button3.Location = New Point(0, 1)
        Button3.Name = "Button3"
        Button3.Size = New Size(398, 33)
        Button3.TabIndex = 8
        Button3.Text = "Admin Information"
        Button3.UseVisualStyleBackColor = False
        ' 
        ' Panel7
        ' 
        Panel7.BackColor = Color.LightGray
        Panel7.Controls.Add(lblNewQuan)
        Panel7.Controls.Add(lblChangeQuan)
        Panel7.Controls.Add(lblPreviousQuan)
        Panel7.Controls.Add(Label16)
        Panel7.Controls.Add(Label17)
        Panel7.Controls.Add(Label19)
        Panel7.Controls.Add(Button2)
        Panel7.Location = New Point(25, 306)
        Panel7.Name = "Panel7"
        Panel7.Size = New Size(398, 116)
        Panel7.TabIndex = 14
        ' 
        ' lblNewQuan
        ' 
        lblNewQuan.AutoSize = True
        lblNewQuan.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblNewQuan.Location = New Point(109, 85)
        lblNewQuan.Name = "lblNewQuan"
        lblNewQuan.Size = New Size(16, 15)
        lblNewQuan.TabIndex = 14
        lblNewQuan.Text = "   "
        ' 
        ' lblChangeQuan
        ' 
        lblChangeQuan.AutoSize = True
        lblChangeQuan.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblChangeQuan.Location = New Point(132, 63)
        lblChangeQuan.Name = "lblChangeQuan"
        lblChangeQuan.Size = New Size(16, 15)
        lblChangeQuan.TabIndex = 13
        lblChangeQuan.Text = "   "
        ' 
        ' lblPreviousQuan
        ' 
        lblPreviousQuan.AutoSize = True
        lblPreviousQuan.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblPreviousQuan.Location = New Point(138, 42)
        lblPreviousQuan.Name = "lblPreviousQuan"
        lblPreviousQuan.Size = New Size(16, 15)
        lblPreviousQuan.TabIndex = 12
        lblPreviousQuan.Text = "   "
        ' 
        ' Label16
        ' 
        Label16.AutoSize = True
        Label16.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label16.Location = New Point(12, 42)
        Label16.Name = "Label16"
        Label16.Size = New Size(126, 15)
        Label16.TabIndex = 9
        Label16.Text = "Previous Quantity:"
        ' 
        ' Label17
        ' 
        Label17.AutoSize = True
        Label17.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label17.Location = New Point(12, 63)
        Label17.Name = "Label17"
        Label17.Size = New Size(122, 15)
        Label17.TabIndex = 10
        Label17.Text = "Change Quantity: "
        ' 
        ' Label19
        ' 
        Label19.AutoSize = True
        Label19.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label19.Location = New Point(12, 85)
        Label19.Name = "Label19"
        Label19.Size = New Size(101, 15)
        Label19.TabIndex = 11
        Label19.Text = "New Quantity: "
        ' 
        ' Button2
        ' 
        Button2.BackColor = Color.DarkSlateGray
        Button2.FlatStyle = FlatStyle.Flat
        Button2.Font = New Font("Arial Rounded MT Bold", 9.75F, FontStyle.Regular, GraphicsUnit.Point, CByte(0))
        Button2.ForeColor = Color.White
        Button2.Location = New Point(0, 1)
        Button2.Name = "Button2"
        Button2.Size = New Size(398, 33)
        Button2.TabIndex = 8
        Button2.Text = "Quantity Change"
        Button2.UseVisualStyleBackColor = False
        ' 
        ' Panel6
        ' 
        Panel6.BackColor = Color.LightGray
        Panel6.Controls.Add(lblReason)
        Panel6.Controls.Add(lblSize)
        Panel6.Controls.Add(lblGender)
        Panel6.Controls.Add(lblLevel)
        Panel6.Controls.Add(lblItemName)
        Panel6.Controls.Add(lblUniformID)
        Panel6.Controls.Add(Label13)
        Panel6.Controls.Add(Label12)
        Panel6.Controls.Add(Label10)
        Panel6.Controls.Add(Label9)
        Panel6.Controls.Add(Label11)
        Panel6.Controls.Add(Label8)
        Panel6.Controls.Add(Button1)
        Panel6.Location = New Point(25, 148)
        Panel6.Name = "Panel6"
        Panel6.Size = New Size(398, 150)
        Panel6.TabIndex = 8
        ' 
        ' lblReason
        ' 
        lblReason.AutoSize = True
        lblReason.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblReason.Location = New Point(70, 129)
        lblReason.Name = "lblReason"
        lblReason.Size = New Size(16, 15)
        lblReason.TabIndex = 18
        lblReason.Text = "   "
        ' 
        ' lblSize
        ' 
        lblSize.AutoSize = True
        lblSize.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblSize.Location = New Point(49, 110)
        lblSize.Name = "lblSize"
        lblSize.Size = New Size(16, 15)
        lblSize.TabIndex = 17
        lblSize.Text = "   "
        ' 
        ' lblGender
        ' 
        lblGender.AutoSize = True
        lblGender.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblGender.Location = New Point(71, 89)
        lblGender.Name = "lblGender"
        lblGender.Size = New Size(16, 15)
        lblGender.TabIndex = 16
        lblGender.Text = "   "
        ' 
        ' lblLevel
        ' 
        lblLevel.AutoSize = True
        lblLevel.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblLevel.Location = New Point(60, 67)
        lblLevel.Name = "lblLevel"
        lblLevel.Size = New Size(16, 15)
        lblLevel.TabIndex = 15
        lblLevel.Text = "   "
        ' 
        ' lblItemName
        ' 
        lblItemName.AutoSize = True
        lblItemName.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblItemName.Location = New Point(97, 47)
        lblItemName.Name = "lblItemName"
        lblItemName.Size = New Size(16, 15)
        lblItemName.TabIndex = 14
        lblItemName.Text = "   "
        ' 
        ' lblUniformID
        ' 
        lblUniformID.AutoSize = True
        lblUniformID.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblUniformID.Location = New Point(97, 27)
        lblUniformID.Name = "lblUniformID"
        lblUniformID.Size = New Size(16, 15)
        lblUniformID.TabIndex = 8
        lblUniformID.Text = "   "
        ' 
        ' Label13
        ' 
        Label13.AutoSize = True
        Label13.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label13.Location = New Point(12, 129)
        Label13.Name = "Label13"
        Label13.Size = New Size(59, 15)
        Label13.TabIndex = 13
        Label13.Text = "Reason:"
        ' 
        ' Label12
        ' 
        Label12.AutoSize = True
        Label12.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label12.Location = New Point(12, 110)
        Label12.Name = "Label12"
        Label12.Size = New Size(39, 15)
        Label12.TabIndex = 12
        Label12.Text = "Size:"
        ' 
        ' Label10
        ' 
        Label10.AutoSize = True
        Label10.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label10.Location = New Point(12, 47)
        Label10.Name = "Label10"
        Label10.Size = New Size(81, 15)
        Label10.TabIndex = 9
        Label10.Text = "Item Name:"
        ' 
        ' Label9
        ' 
        Label9.AutoSize = True
        Label9.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label9.Location = New Point(12, 67)
        Label9.Name = "Label9"
        Label9.Size = New Size(46, 15)
        Label9.TabIndex = 10
        Label9.Text = "Level:"
        ' 
        ' Label11
        ' 
        Label11.AutoSize = True
        Label11.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label11.Location = New Point(12, 27)
        Label11.Name = "Label11"
        Label11.Size = New Size(80, 15)
        Label11.TabIndex = 8
        Label11.Text = "Uniform ID:"
        ' 
        ' Label8
        ' 
        Label8.AutoSize = True
        Label8.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label8.Location = New Point(12, 89)
        Label8.Name = "Label8"
        Label8.Size = New Size(59, 15)
        Label8.TabIndex = 11
        Label8.Text = "Gender:"
        ' 
        ' Button1
        ' 
        Button1.BackColor = Color.DarkSlateGray
        Button1.FlatStyle = FlatStyle.Flat
        Button1.Font = New Font("Arial Rounded MT Bold", 9.75F, FontStyle.Regular, GraphicsUnit.Point, CByte(0))
        Button1.ForeColor = Color.White
        Button1.Location = New Point(0, 1)
        Button1.Name = "Button1"
        Button1.Size = New Size(398, 23)
        Button1.TabIndex = 8
        Button1.Text = "Item Information"
        Button1.UseVisualStyleBackColor = False
        ' 
        ' Panel5
        ' 
        Panel5.BackColor = Color.LightGray
        Panel5.Controls.Add(lblLogId)
        Panel5.Controls.Add(lblAction)
        Panel5.Controls.Add(Label7)
        Panel5.Controls.Add(lblTime)
        Panel5.Controls.Add(lblDate)
        Panel5.Controls.Add(Label6)
        Panel5.Controls.Add(Label5)
        Panel5.Controls.Add(Label4)
        Panel5.Location = New Point(25, 51)
        Panel5.Name = "Panel5"
        Panel5.Size = New Size(398, 90)
        Panel5.TabIndex = 1
        ' 
        ' lblLogId
        ' 
        lblLogId.AutoSize = True
        lblLogId.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblLogId.ForeColor = Color.Black
        lblLogId.Location = New Point(65, 8)
        lblLogId.Name = "lblLogId"
        lblLogId.Size = New Size(16, 15)
        lblLogId.TabIndex = 3
        lblLogId.Text = "   "
        ' 
        ' lblAction
        ' 
        lblAction.AutoSize = True
        lblAction.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblAction.Location = New Point(138, 68)
        lblAction.Name = "lblAction"
        lblAction.Size = New Size(16, 15)
        lblAction.TabIndex = 7
        lblAction.Text = "   "
        ' 
        ' Label7
        ' 
        Label7.AutoSize = True
        Label7.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label7.Location = New Point(12, 68)
        Label7.Name = "Label7"
        Label7.Size = New Size(125, 15)
        Label7.TabIndex = 6
        Label7.Text = "Action Performed:"
        ' 
        ' lblTime
        ' 
        lblTime.AutoSize = True
        lblTime.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblTime.Location = New Point(55, 49)
        lblTime.Name = "lblTime"
        lblTime.Size = New Size(16, 15)
        lblTime.TabIndex = 5
        lblTime.Text = "   "
        ' 
        ' lblDate
        ' 
        lblDate.AutoSize = True
        lblDate.Font = New Font("Arial Rounded MT Bold", 9.75F)
        lblDate.Location = New Point(55, 29)
        lblDate.Name = "lblDate"
        lblDate.Size = New Size(16, 15)
        lblDate.TabIndex = 4
        lblDate.Text = "   "
        ' 
        ' Label6
        ' 
        Label6.AutoSize = True
        Label6.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label6.Location = New Point(12, 49)
        Label6.Name = "Label6"
        Label6.Size = New Size(46, 15)
        Label6.TabIndex = 2
        Label6.Text = "Time: "
        ' 
        ' Label5
        ' 
        Label5.AutoSize = True
        Label5.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label5.Location = New Point(12, 29)
        Label5.Name = "Label5"
        Label5.Size = New Size(42, 15)
        Label5.TabIndex = 1
        Label5.Text = "Date:"
        ' 
        ' Label4
        ' 
        Label4.AutoSize = True
        Label4.Font = New Font("Arial Rounded MT Bold", 9.75F)
        Label4.Location = New Point(12, 8)
        Label4.Name = "Label4"
        Label4.Size = New Size(52, 15)
        Label4.TabIndex = 0
        Label4.Text = "Log ID:"
        ' 
        ' Panel4
        ' 
        Panel4.BackColor = Color.MediumAquamarine
        Panel4.BorderStyle = BorderStyle.FixedSingle
        Panel4.Controls.Add(Label3)
        Panel4.Location = New Point(25, 16)
        Panel4.Name = "Panel4"
        Panel4.Size = New Size(398, 26)
        Panel4.TabIndex = 0
        ' 
        ' Label3
        ' 
        Label3.AutoSize = True
        Label3.Font = New Font("Arial Rounded MT Bold", 12F, FontStyle.Regular, GraphicsUnit.Point, CByte(0))
        Label3.ForeColor = Color.Black
        Label3.Location = New Point(39, 3)
        Label3.Name = "Label3"
        Label3.Size = New Size(308, 18)
        Label3.TabIndex = 115
        Label3.Text = "📦 INVENTORY LOG ENTRY DETAILS  "
        ' 
        ' Label2
        ' 
        Label2.AutoSize = True
        Label2.Font = New Font("Arial Rounded MT Bold", 15.75F, FontStyle.Regular, GraphicsUnit.Point, CByte(0))
        Label2.ForeColor = Color.White
        Label2.Location = New Point(8, 2)
        Label2.Name = "Label2"
        Label2.Size = New Size(288, 24)
        Label2.TabIndex = 112
        Label2.Text = "🖨️ Print Preview - Log Entry"
        ' 
        ' Panel2
        ' 
        Panel2.BackColor = Color.LightGray
        Panel2.Controls.Add(Label1)
        Panel2.Controls.Add(Panel3)
        Panel2.Location = New Point(13, 41)
        Panel2.Name = "Panel2"
        Panel2.Size = New Size(499, 619)
        Panel2.TabIndex = 116
        ' 
        ' Label1
        ' 
        Label1.AutoSize = True
        Label1.Font = New Font("Arial Rounded MT Bold", 12.75F, FontStyle.Regular, GraphicsUnit.Point, CByte(0))
        Label1.ForeColor = Color.Black
        Label1.Location = New Point(148, 4)
        Label1.Name = "Label1"
        Label1.Size = New Size(171, 20)
        Label1.TabIndex = 113
        Label1.Text = "Paper Area Preview"
        ' 
        ' Panel1
        ' 
        Panel1.BackColor = Color.DarkSlateGray
        Panel1.BorderStyle = BorderStyle.Fixed3D
        Panel1.Controls.Add(btnPrint)
        Panel1.Controls.Add(Label2)
        Panel1.Font = New Font("Segoe UI", 11.25F, FontStyle.Regular, GraphicsUnit.Point, CByte(0))
        Panel1.ForeColor = Color.White
        Panel1.Location = New Point(2, 1)
        Panel1.Name = "Panel1"
        Panel1.Size = New Size(523, 35)
        Panel1.TabIndex = 115
        ' 
        ' btnPrint
        ' 
        btnPrint.Font = New Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point, CByte(0))
        btnPrint.ForeColor = Color.Black
        btnPrint.Location = New Point(411, 3)
        btnPrint.Name = "btnPrint"
        btnPrint.Size = New Size(97, 23)
        btnPrint.TabIndex = 113
        btnPrint.Text = "🖨️ Print"
        btnPrint.UseVisualStyleBackColor = True
        ' 
        ' PrintDocument1
        ' 
        ' 
        ' PrintPreviewDialog1
        ' 
        PrintPreviewDialog1.AutoScrollMargin = New Size(0, 0)
        PrintPreviewDialog1.AutoScrollMinSize = New Size(0, 0)
        PrintPreviewDialog1.ClientSize = New Size(400, 300)
        PrintPreviewDialog1.Enabled = True
        PrintPreviewDialog1.Icon = CType(resources.GetObject("PrintPreviewDialog1.Icon"), Icon)
        PrintPreviewDialog1.Name = "PrintPreviewDialog1"
        PrintPreviewDialog1.Visible = False
        ' 
        ' Label21
        ' 
        Label21.AutoSize = True
        Label21.Font = New Font("Arial Rounded MT Bold", 9.75F, FontStyle.Regular, GraphicsUnit.Point, CByte(0))
        Label21.ForeColor = Color.Firebrick
        Label21.Location = New Point(122, 535)
        Label21.Name = "Label21"
        Label21.Size = New Size(206, 15)
        Label21.TabIndex = 19
        Label21.Text = "Inventory Management System"
        ' 
        ' frmPrintPreview
        ' 
        AutoScaleDimensions = New SizeF(7F, 15F)
        AutoScaleMode = AutoScaleMode.Font
        BackColor = Color.DarkSlateGray
        ClientSize = New Size(527, 667)
        Controls.Add(Panel2)
        Controls.Add(Panel1)
        Name = "frmPrintPreview"
        Text = "frmPrintPreview"
        Panel3.ResumeLayout(False)
        Panel3.PerformLayout()
        Panel8.ResumeLayout(False)
        Panel8.PerformLayout()
        Panel7.ResumeLayout(False)
        Panel7.PerformLayout()
        Panel6.ResumeLayout(False)
        Panel6.PerformLayout()
        Panel5.ResumeLayout(False)
        Panel5.PerformLayout()
        Panel4.ResumeLayout(False)
        Panel4.PerformLayout()
        Panel2.ResumeLayout(False)
        Panel2.PerformLayout()
        Panel1.ResumeLayout(False)
        Panel1.PerformLayout()
        ResumeLayout(False)
    End Sub

    Friend WithEvents Panel3 As Panel
    Friend WithEvents Panel4 As Panel
    Private WithEvents Label3 As Label
    Private WithEvents Label2 As Label
    Friend WithEvents Panel2 As Panel
    Private WithEvents Label1 As Label
    Friend WithEvents Panel1 As Panel
    Friend WithEvents Panel5 As Panel
    Friend WithEvents Label6 As Label
    Friend WithEvents Label5 As Label
    Friend WithEvents Label4 As Label
    Friend WithEvents lblLogId As Label
    Friend WithEvents lblDate As Label
    Friend WithEvents lblTime As Label
    Friend WithEvents Label7 As Label
    Friend WithEvents lblAction As Label
    Friend WithEvents Panel6 As Panel
    Friend WithEvents Button1 As Button
    Friend WithEvents Label10 As Label
    Friend WithEvents Label9 As Label
    Friend WithEvents Label11 As Label
    Friend WithEvents Label8 As Label
    Friend WithEvents Label12 As Label
    Friend WithEvents Panel7 As Panel
    Friend WithEvents Label16 As Label
    Friend WithEvents Label17 As Label
    Friend WithEvents Label19 As Label
    Friend WithEvents Button2 As Button
    Friend WithEvents Label13 As Label
    Friend WithEvents Panel8 As Panel
    Friend WithEvents Label14 As Label
    Friend WithEvents Label15 As Label
    Friend WithEvents Button3 As Button
    Friend WithEvents Label20 As Label
    Friend WithEvents Label18 As Label
    Friend WithEvents lblPrintDate As Label
    Friend WithEvents lblUniformID As Label
    Friend WithEvents lblItemName As Label
    Friend WithEvents lblLevel As Label
    Friend WithEvents lblGender As Label
    Friend WithEvents lblSize As Label
    Friend WithEvents lblReason As Label
    Friend WithEvents lblPreviousQuan As Label
    Friend WithEvents lblNewQuan As Label
    Friend WithEvents lblChangeQuan As Label
    Friend WithEvents lblAdminName As Label
    Friend WithEvents lblAdminID As Label
    Friend WithEvents btnPrint As Button
    Friend WithEvents PrintDocument1 As Printing.PrintDocument
    Friend WithEvents PrintPreviewDialog1 As PrintPreviewDialog
    Friend WithEvents Label21 As Label
End Class
